/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_sgool_dll_UpFreeTray */

#ifndef _Included_cn_sgool_dll_UpFreeTray
#define _Included_cn_sgool_dll_UpFreeTray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sgool_dll_UpFreeTray
 * Method:    connectToAppServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_UpFreeTray_connectToAppServer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_sgool_dll_UpFreeTray
 * Method:    upFreeTray
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_UpFreeTray_upFreeTray
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
