/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_sgool_dll_Classify */

#ifndef _Included_cn_sgool_dll_Classify
#define _Included_cn_sgool_dll_Classify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sgool_dll_Classify
 * Method:    connectToAppServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_Classify_connectToAppServer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_sgool_dll_Classify
 * Method:    upOcvFxResult16
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_Classify_upOcvFxResult16
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     cn_sgool_dll_Classify
 * Method:    upOcvFxResultMany
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_Classify_upOcvFxResultMany
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
