/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_sgool_dll_SelectBattInfo */

#ifndef _Included_cn_sgool_dll_SelectBattInfo
#define _Included_cn_sgool_dll_SelectBattInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sgool_dll_SelectBattInfo
 * Method:    connectToAppServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_SelectBattInfo_connectToAppServer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_sgool_dll_SelectBattInfo
 * Method:    getTrayBattInfoDC
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_SelectBattInfo_getTrayBattInfoDC
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     cn_sgool_dll_SelectBattInfo
 * Method:    getTrayBattInfoDC2
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_sgool_dll_SelectBattInfo_getTrayBattInfoDC2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
